apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  labels:
    app: gitlab-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: gitlab